services:
  - type: web
    name: farm-backend
    runtime: node
    plan: starter

    buildCommand: |
      npm ci
      npm install -g @nestjs/cli
      npx prisma generate
      npm run build

    startCommand: node dist/src/main.js

    envVars:
      - key: NODE_ENV
        value: production