services:
  - type: web
    name: farm-backend
    runtime: node
    plan: starter

    buildCommand: |
      npm install
      npx prisma generate
      npm run build

    startCommand: |
      npx prisma migrate deploy
      npm run start:prod

    envVars:
      - key: NODE_ENV
        value: production