import { ConfigService } from '@nestjs/config';
import { PrismaService } from '../database/prisma.service';
import { DepositService } from '../deposit/deposit.service';
import { WithdrawService } from '../withdraw/withdraw.service';
import { PaystackService } from '../paystack/paystack.service';
import { IvorypayService } from '../ivorypay/ivorypay.service';
import { NotificationsService } from '../notifications/notifications.service';
import { WebsocketGateway } from '../websocket/websocket.gateway';
import { RedisService } from '../common/redis/redis.service';
import type { Queue } from 'bull';
export declare class WebhookService {
    private readonly prisma;
    private readonly depositService;
    private readonly withdrawService;
    private readonly websocket;
    private readonly notificationsService;
    private readonly cfg;
    private readonly paystackService;
    private readonly ivorypayService;
    private readonly webhookQueue;
    private readonly redisService?;
    private readonly logger;
    constructor(prisma: PrismaService, depositService: DepositService, withdrawService: WithdrawService, websocket: WebsocketGateway, notificationsService: NotificationsService, cfg: ConfigService, paystackService: PaystackService, ivorypayService: IvorypayService, webhookQueue: Queue, redisService?: RedisService | undefined);
    private getRedisClient;
    handlePaystackWebhook(payload: any, verified?: boolean, rawBody?: string, signature?: string): Promise<{
        received: boolean;
    }>;
    handleIvorypayWebhook(payload: any, verified?: boolean): Promise<{
        received: boolean;
    }>;
    private logWebhook;
    private rejectWebhook;
    private verifyProviderPayload;
    private getIvorypayReference;
    private extractUuidFromString;
    private buildIvorypayReferenceCandidates;
    private verifyIvorypayWebhookTransaction;
    private isIvorypayVerifiedAmountAcceptable;
    private resolveIvorypayInternalReference;
    private resolveIvorypayDepositAndTransaction;
    private isIvorypaySuccessEvent;
    private isIvorypayFailureEvent;
    private fallbackAlert;
    private getEventId;
    private isReplay;
    private markProcessed;
    private detectPotentialFraud;
    private finalizeDeposit;
    fixStuckDeposits(): Promise<void>;
    private cleanupStaleFailedDeposits;
    private finalizePendingDepositWithTransaction;
    private completePendingTransaction;
    private creditPendingTransactionDeposit;
    private creditPendingDepositWithWallet;
    private finalizeWithdrawal;
    private completeTransactionWithdrawal;
    private failTransactionWithdrawal;
    private emitWithdrawalUpdate;
    private normalizeAmount;
    private retryVerifyTransaction;
    private getFarmAmountForCredit;
    handlePaystackWebhookProcessing(payload: any): Promise<void>;
    private acquireLock;
    private releaseLock;
    handleIvorypayWebhookProcessing(payload: any): Promise<void>;
}
