import { PrismaService } from '../database/prisma.service';
import { PaystackService } from '../paystack/paystack.service';
import { IvorypayService } from '../ivorypay/ivorypay.service';
import { WebsocketGateway } from '../websocket/websocket.gateway';
import { CacheService } from '../common/cache/cache.service';
import { NotificationsService } from '../notifications/notifications.service';
import { CurrencyConversionService } from '../currency/currency-conversion.service';
export declare class DepositService {
    private prisma;
    private paystack;
    private ivorypay;
    private websocket;
    private cache;
    private notificationsService;
    private currencyConversionService;
    private readonly logger;
    constructor(prisma: PrismaService, paystack: PaystackService, ivorypay: IvorypayService, websocket: WebsocketGateway, cache: CacheService, notificationsService: NotificationsService, currencyConversionService: CurrencyConversionService);
    createDeposit(userId: string, dto: any): Promise<{
        data: {
            provider: string;
            reference: string;
            payment_url: any;
            authorization_url: any;
        };
        message: string;
        success?: undefined;
        payment_url?: undefined;
        authorization_url?: undefined;
        reference?: undefined;
        deposit?: undefined;
    } | {
        success: boolean;
        payment_url: string | null;
        authorization_url: string | null;
        reference: string;
        deposit: {
            id: string;
            status: import("@prisma/client").$Enums.DepositStatus;
            currency: string;
            userId: string;
            amount: number;
            total: number;
            fee: number;
            paymentMethod: import("@prisma/client").$Enums.PaymentMethod;
            reference: string;
            providerRef: string | null;
            providerTransactionId: string | null;
            providerReference: string | null;
            checkoutId: string | null;
            paymentReference: string | null;
            merchantReference: string | null;
            providerPayload: import("@prisma/client/runtime/library").JsonValue | null;
            verificationPayload: import("@prisma/client/runtime/library").JsonValue | null;
            blockchainTransactionHash: string | null;
            verifiedAt: Date | null;
            creditedAt: Date | null;
            webhookReceived: Date | null;
            verificationAttempts: number | null;
            createdAt: Date;
            updatedAt: Date;
            provider: string | null;
        };
        data?: undefined;
        message?: undefined;
    }>;
    getUserDeposits(userId: string): Promise<{
        success: boolean;
        data: {
            id: string;
            status: import("@prisma/client").$Enums.DepositStatus;
            currency: string;
            userId: string;
            amount: number;
            total: number;
            fee: number;
            paymentMethod: import("@prisma/client").$Enums.PaymentMethod;
            reference: string;
            providerRef: string | null;
            providerTransactionId: string | null;
            providerReference: string | null;
            checkoutId: string | null;
            paymentReference: string | null;
            merchantReference: string | null;
            providerPayload: import("@prisma/client/runtime/library").JsonValue | null;
            verificationPayload: import("@prisma/client/runtime/library").JsonValue | null;
            blockchainTransactionHash: string | null;
            verifiedAt: Date | null;
            creditedAt: Date | null;
            webhookReceived: Date | null;
            verificationAttempts: number | null;
            createdAt: Date;
            updatedAt: Date;
            provider: string | null;
        }[];
    }>;
    getWalletBalance(userId: string): Promise<{
        balance: number | import("@prisma/client/runtime/library").Decimal;
        locked_balance: number | import("@prisma/client/runtime/library").Decimal;
    }>;
    getDepositById(id: string, userId?: string): Promise<{
        id: string;
        status: import("@prisma/client").$Enums.DepositStatus;
        currency: string;
        userId: string;
        amount: number;
        total: number;
        fee: number;
        paymentMethod: import("@prisma/client").$Enums.PaymentMethod;
        reference: string;
        providerRef: string | null;
        providerTransactionId: string | null;
        providerReference: string | null;
        checkoutId: string | null;
        paymentReference: string | null;
        merchantReference: string | null;
        providerPayload: import("@prisma/client/runtime/library").JsonValue | null;
        verificationPayload: import("@prisma/client/runtime/library").JsonValue | null;
        blockchainTransactionHash: string | null;
        verifiedAt: Date | null;
        creditedAt: Date | null;
        webhookReceived: Date | null;
        verificationAttempts: number | null;
        createdAt: Date;
        updatedAt: Date;
        provider: string | null;
    } | null>;
    finalizeSuccessfulDeposit(reference: string): Promise<boolean>;
    failDeposit(reference: string, reason?: string): Promise<boolean>;
    private finalizePendingDepositWithTransaction;
    private completePendingTransaction;
    private creditPendingTransactionDeposit;
    private creditPendingDepositWithWallet;
    private invalidateFinancialCaches;
    private normalizeAmount;
}
