name: Static Analysis - Semgrep

on:
  pull_request:
  push:

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          args: --config auto
