import { PrismaService } from '../database/prisma.service';
import { AuthService } from '../auth/auth.service';
import { SecurityService } from '../security/security.service';
import { PaystackService } from '../paystack/paystack.service';
import { IvorypayService } from '../ivorypay/ivorypay.service';
import { CreateWithdrawDto } from './dto/create-withdraw.dto';
import { CacheService } from '../common/cache/cache.service';
import { NotificationsService } from '../notifications/notifications.service';
import { CurrencyConversionService } from '../currency/currency-conversion.service';
export declare class WithdrawService {
    private prisma;
    private authService;
    private securityService;
    private paystack;
    private ivorypay;
    private cache;
    private notificationsService;
    private readonly currencyConversionService;
    private readonly logger;
    constructor(prisma: PrismaService, authService: AuthService, securityService: SecurityService, paystack: PaystackService, ivorypay: IvorypayService, cache: CacheService, notificationsService: NotificationsService, currencyConversionService: CurrencyConversionService);
    createWithdrawal(userId: string, dto: CreateWithdrawDto): Promise<{
        success: boolean;
        reference: string;
        withdrawal: {
            id: string;
            status: string;
            currency: string;
            userId: string;
            amount: number;
            total: number;
            fee: number;
            reference: string;
            createdAt: Date;
            updatedAt: Date;
            method: string;
            settlement: number;
            accountName: string | null;
            accountNumber: string | null;
            bankName: string | null;
            phoneNumber: string | null;
            cryptoAddress: string | null;
            cryptoAsset: string | null;
            network: string | null;
            rejectionReason: string | null;
        };
    }>;
    getUserWithdrawals(userId: string): Promise<{
        id: string;
        status: string;
        currency: string;
        userId: string;
        amount: number;
        total: number;
        fee: number;
        reference: string;
        createdAt: Date;
        updatedAt: Date;
        method: string;
        settlement: number;
        accountName: string | null;
        accountNumber: string | null;
        bankName: string | null;
        phoneNumber: string | null;
        cryptoAddress: string | null;
        cryptoAsset: string | null;
        network: string | null;
        rejectionReason: string | null;
    }[]>;
    getProviderNetworks(token?: string): {
        success: boolean;
        token: string;
        networks: string[];
    };
    getWithdrawal(id: string, userId?: string): Promise<{
        id: string;
        status: string;
        currency: string;
        userId: string;
        amount: number;
        total: number;
        fee: number;
        reference: string;
        createdAt: Date;
        updatedAt: Date;
        method: string;
        settlement: number;
        accountName: string | null;
        accountNumber: string | null;
        bankName: string | null;
        phoneNumber: string | null;
        cryptoAddress: string | null;
        cryptoAsset: string | null;
        network: string | null;
        rejectionReason: string | null;
    } | null>;
    getWithdrawalStatus(reference: string, userId: string): Promise<any>;
    private processWithdrawal;
    private processCryptoWithdrawal;
    markAsSuccess(reference: string): Promise<boolean>;
    private creditPlatformFee;
    rejectWithdrawal(reference: string, reason: string): Promise<boolean>;
    private formatMpesaNumber;
    private resolveBankCode;
}
